version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stc-service
#      - SPRING_DATASOURCE_USERNAME=stc
#      - SPRING_DATASOURCE_PASSWORD=stc@pass
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=stc
      - POSTGRES_PASSWORD=stc@pass